FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 sudo openssh-server acl && \
    mkdir -p /run/sshd /etc/ssh/sshd_config.d && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash", "-c", "while true; do sleep 1000; done"]